version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.8

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt"}}
      - run:
          name: Flake8
          command: |
            . venv/bin/activate
            flake8

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
